export const BODY_CONDITION_SCORE_FETCH_ALL = "BODY_CONDITION_SCORE_FETCH_ALL";
export const BODY_CONDITION_SCORE_FETCH_ENTITY = "BODY_CONDITION_SCORE_FETCH_ENTITY";
export const BODY_CONDITION_SCORE_CREATE_ENTITY = "BODY_CONDITION_SCORE_CREATE_ENTITY";
export const BODY_CONDITION_SCORE_UPDATE_ENTITY = "BODY_CONDITION_SCORE_UPDATE_ENTITY";
export const BODY_CONDITION_SCORE_DELETE_ENTITY = "BODY_CONDITION_SCORE_DELETE_ENTITY";
export const BODY_CONDITION_SCORE_RESET = "BODY_CONDITION_SCORE_RESET";

export const BODY_WEIGHT_MANAGEMENT_FETCH_ALL = "BODY_WEIGHT_MANAGEMENT_FETCH_ALL";
export const BODY_WEIGHT_MANAGEMENT_FETCH_ENTITY = "BODY_WEIGHT_MANAGEMENT_FETCH_ENTITY";
export const BODY_WEIGHT_MANAGEMENT_CREATE_ENTITY = "BODY_WEIGHT_MANAGEMENT_CREATE_ENTITY";
export const BODY_WEIGHT_MANAGEMENT_UPDATE_ENTITY = "BODY_WEIGHT_MANAGEMENT_UPDATE_ENTITY";
export const BODY_WEIGHT_MANAGEMENT_DELETE_ENTITY = "BODY_WEIGHT_MANAGEMENT_DELETE_ENTITY";
export const BODY_WEIGHT_MANAGEMENT_RESET = "BODY_WEIGHT_MANAGEMENT_RESET";

// deworming
export const SET_DEWORMING_LIST = "SET_DEWORMING_LIST";
export const SET_DEWORMING_DETAILS = "SET_DEWORMING_DETAILS";

// siple-prescription
export const SIMPLE_PRESCRIPTION_MEDICINE_CHANGE_DEWORMING = "SIMPLE_PRESCRIPTION_MEDICINE_CHANGE_DEWORMING";
export const SIMPLE_PRESCRIPTION_MEDICINE_CHANGE_DEHORNING = "SIMPLE_PRESCRIPTION_MEDICINE_CHANGE_DEHORNING";


