export default {
    dashboard: "Home/Animal Mgmt",
    farmAdmin: "Home/Farm Admin",
    myAccount: "Home/Farm Admin/MyAccount",
    profileDetails: "Home/Profile Details",
    farmProfile: "Home/Farm Profile",
    profileInfo: "Home/Animal Mgmt/Register Animal",
    breedInfo: "Home/Animal Mgmt/Register Animal",
    morphologicalInfo: "Home/Animal Mgmt/Register Animal",
    animalListing: "Home/Animal Mgmt/Animal Listing",
    calfHeiferListing: "Home/Calf-Heifer Listing",
    cattleDetails: "Home/Animal Mgmt/Animal Listing",
    calfHeiferDetails: "Home/Animal Mgmt/Animal Listing",
    animalDetails: "Home/Animal Mgmt/Animal Details",
    observationListing: "Home/Health/Observation Listing",
    recordObservation: "Home/Health/Observation",
    prescription: "Home/Health/Observation",
    observationDetails: "Home/Health/Observation Summary",
    vaccinationListing: "Home/Health/Vaccination",
    vaccinationDetails: "Home/Health/Record Vaccination",
    recordVaccination: "Home/Health/Record Vaccination",
    dewormingListing: "Home/Health/Deworming",
    dewormingDetails: "Home/Health/Deworming Summary",
    recordDeworming: "Home/Health/Record Deworming"
};
